export PATH=$PATH:/home/root/ffmpeg
export MODULE_DATA_DIR=/media/sdcard/data
export MODULE_APP_DIR=/apps/monitoring
export SCRIPTS=/home/root/scripts
export REBOOT_COUNT_PATH=/home/root/REBOOT_COUNT
export MODULE_PACKAGES_DIR=/media/sdcard/packages
export ROTATION_SPEED=/home/root/ROTATION_SPEED
export ROTATION_DURATION=/home/root/ROTATION_DURATION
export REBOOT_COUNT=`cat /home/root/REBOOT_COUNT` 
export SERIAL_NUMBER=`cat /factory/serial_number`